### ISSUE TITLE
支持百家云吗

### ISSUE THREAD

**Issue by account310** [wxx9248/baijiayunxiao-downloader#188]
支持百家云吗，我看只有百家云校，是否支持*.at.baijiayun.com 这个网址

**Comment by account310** [comment]
![image](https://github.com/wxx9248/baijiayunxiao-downloader/assets/59204974/b2ba441f-0d87-4c62-956a-ac02ea7293b2)

**Comment by account310** [comment]
这里头上面这种地址，里头是有回放的

**Comment by wxx9248** [comment]
我没有百家云的号，没法测试
你能提出来回放CDN的地址的话，应该没啥问题，稍微换一下hook点就能用

**Comment by wxx9248** [comment]
重复 #221 https://github.com/wxx9248/baijiayunxiao-downloader/issues/221#issuecomment-1862224496
