### ISSUE TITLE
能否增加支持云端课堂

### ISSUE THREAD

**Issue by ShanPoYang1** [wxx9248/baijiayunxiao-downloader#221]
能否增加支持百家云云端课堂，绕过检测，云端课堂屏蔽了浏览器网页视频播放，显示不支持的终端类型。

**Comment by wxx9248** [comment]
我没有百家云的账号来抓API
不太清楚百家云校和百家云的账号通不通用，如果通用的话我过两天考完试可以搞一下

**Comment by wxx9248** [comment]
两个平台账号不互通，我没办法增加支持。
如果你想测试能不能直接用的话，可以把这里的`match`改成你要的网址的匹配：`https://github.com/wxx9248/baijiayunxiao-downloader/blob/0326b9b9fb18f4cc314cd2518a85e2c94ce03dd4/vite.config.ts#L30C20-L30C20`
